#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                           SaberCore 3.0                                     #####
#####                        Created By Driftay                                   #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################
#<-------------------------------------->NOTES<-------------------------------------->#
#All Color Codes Can Be Used!
#Refer to: https://wiki.ess3.net/mc/
#Enable and Disable Any Feature by Simply Switching Variable to true or false!
#<-------------------------------------->NOTES<-------------------------------------->#
############################################################
# +------------------------------------------------------+ #
# |                        MISC                          | #
# +------------------------------------------------------+ #
############################################################
useAntiZombieBaby: true #Denies baby Zombies & baby Zombie Pigmen from spawning
reduceIronGolemHealth: true
denyIronGolemsTargetZombies: true #Denies Iron Golems Targeting on Zombies
ironGolemHealth: 5.0 #5.0 = 10 Hearts
denyExplosionDamage: true #Denies all explosion damage to players
useAntiMobAI: true #Denies Mobs from moving
useAntiMobTargeting: true #Denies Mobs from targeting players
lffCooldown: 30 #Lff Command Cooldown in Seconds
slowChatTime: 0 #Timer for SlowChat Command.
enderPearlCooldown: 15 #Cooldown in Seconds
useAntiCobbleMonster: true #Denies Lava and Water being mixed to possibly make cobble monsters
useAutoRespawn: true #AutoRespawn players on death
useAntiWildernessSpawner: true #Denies Spawners from spawning when in placed in Wilderness (Avoids Boosting and Vaults)
useAntiBoatPlacement: true #Denies players from placing and using Minecarts and Boats (2 Highly glitchable items in factions)
denyPistonFarming: true #Will Not allow crops to be broken by pistons (Lag Machines can be turned into automatic farms)
instaSpongeBreak: true #Allows Sponges to be instantly breakable
cancelDragonEggTeleport: true #DragonEggs will not teleport when right clicked
denyNaturalMobSpawning: true #Denies all natural mobs from spawning
denyBlazeWaterDamage: true #Blazes will not take damage from water
useBookDisenchant: true #Left clicking a enchantment table with a enchanted book will convert it back to its original form (HCF Style)
useOreTracker: false #Adds a HCF Style ore tracker to pickaxes.

############################################################
# +------------------------------------------------------+ #
# |                    Chunkbusters                      | #
# +------------------------------------------------------+ #
############################################################
Chunkbuster:
  Enabled: true
  Warmup: 10 #In Seconds, timer will run before busting chunk.
  Async-Mode: false #Will Destroy Layer By Layer if Enabled.
  Hologram:
    Enabled: true #Requires Holographic Displays
    Format: '&c&l[!] &7ChunkBuster' #Hologram Format for Chunkbuster When Placed
  Item:
    DisplayName: '&c&lChunkBuster'
    Lore:
      - '&f'
      - '&7&o(( Tip: Placing this &c&ochunkbuster&7&o will &a&oautomatically'
      - '&7&oremove the chunk upon &a&oplacement&7&o! ))'
      - '&f'
      - '&4&l* &cObtained from: &fstore.mystore.com'

############################################################
# +------------------------------------------------------+ #
# |                   Harvester Hoes                     | #
# +------------------------------------------------------+ #
############################################################
HarvesterHoe:
  Enabled: true
  AutoSell: false #Will Automatically Sell All Sugar Cane Broken
  SugarCanePrice: 0.5 #The Cost Per Sugar Cane
  Item:
    DisplayName: '&a&lHarvester Hoe'
    Lore:
      - '&f'
      - '&7&o(( Tip: When Mining &a&oSugar Cane&7&o will &f&oautomatically'
      - '&7&oplace it &f&odirectly &7&ointo your &a&oinventory!'
      - '&f'
      - '&4&l* &cObtained from: &fstore.mystore.com'

############################################################
# +------------------------------------------------------+ #
# |                    Shockwaves                        | #
# +------------------------------------------------------+ #
############################################################
Shockwave:
  Enabled: true #Enable or Disable Shockwaves
  Log-Core-Protect: false #REQUIRES CORE PROTECT TO BE INSTALLED!
  Efficiency-Level: 5
  Unbreaking-Level: 3
  Item:
    DisplayName: '&c&lShockwave Tool'
    Lore:
      - '&f'
      - '&4&l* &cRadius: &f{radius}x{radius}'

############################################################
# +------------------------------------------------------+ #
# |                    SmeltWand                         | #
# +------------------------------------------------------+ #
############################################################
Smelt-Wand:
  Item:
    Glow: true
    Type: STICK
    Display-Name: '&b&lSmelt Wand'
    Lore:
      - '&f'
      - '&4&l* &cUses: &f{uses}'
      - '&f'
      - '&7&o(( Tip: When interacting with &b&oa chest&7&o will'
      - '&f&osmelt &7&oall items in the &b&ochest!'
      - '&f'
      - '&4&l* &cObtained from: &fstore.mystore.com'

############################################################
# +------------------------------------------------------+ #
# |                    CraftWand                         | #
# +------------------------------------------------------+ #
############################################################
Craft-Wand:
  Item:
    Glow: true
    Type: STICK
    Display-Name: '&b&lCraft Wand'
    Lore:
      - '&f'
      - '&4&l* &cUses: &f{uses}'
      - '&f'
      - '&7&o(( Tip: When interacting with &b&oa chest&7&o will'
      - '&f&ocraft &7&oall blocks in the &b&ochest!'
      - '&f'
      - '&4&l* &cObtained from: &fstore.mystore.com'

############################################################
# +------------------------------------------------------+ #
# |                  LightningWand                       | #
# +------------------------------------------------------+ #
############################################################
Lightning-Wand:
  Item:
    Glow: true
    Type: BLAZE_ROD
    Display-Name: '&e&lLightning Wand'
    Lore:
      - '&f'
      - '&4&l* &cUses: &f{uses}'
      - '&f'
      - '&7&o(( Tip: When interacting with &e&oa creeper&7&o will'
      - '&f&oset &7&ocreeper to be a powered &e&ocreeper!'
      - '&f'
      - '&4&l* &cObtained from: &fstore.mystore.com'

############################################################
# +------------------------------------------------------+ #
# |                     SandWand                         | #
# +------------------------------------------------------+ #
############################################################
Sand-Wand:
  Removable-Blocks:
    - GRAVEL
    - RED_SAND
    - SAND
  Item:
    Glow: true
    Type: STICK
    Display-Name: '&e&lSand Wand'
    Lore:
      - '&f'
      - '&4&l* &cUses: &f{uses}'
      - '&f'
      - '&7&o(( Tip: When interacting with &e&osand&7&o will'
      - '&f&oset &7&oall sand stacked &e&oair!'
      - '&f'
      - '&4&l* &cObtained from: &fstore.mystore.com'

############################################################
# +------------------------------------------------------+ #
# |                    PlayerInfo                        | #
# +------------------------------------------------------+ #
############################################################
PlayerInfo:
  Format:
    - "&b{player}'s Information"
    - "&7 * XYZ: {x}, {y}, {z}"
    - "&7 * Health: {health}"
    - "&7 * Fly Speed: {flyspeed}"
    - "&7 * Ping: {ping}"

############################################################
# +------------------------------------------------------+ #
# |                  SpawnerSponges                      | #
# +------------------------------------------------------+ #
############################################################
SpawnerSponge: #Spawners will act as sponges and soak lava and water up
  #NOTE: Sponges function the same way!
  Enabled: true
  Radius: 3

############################################################
# +------------------------------------------------------+ #
# |                    ChatFilter                        | #
# +------------------------------------------------------+ #
############################################################
ChatFilter:
  Format: '&b&l[Filtered] &e{player}&f: {message}'
  Filtered-Words:
    - nigger
    - faggot
    - queer
    - slut
    - whore
  Whitelisted-Links:
    - youtube.com
    - gyazo.com
    - discord.gg
    - twitter.com
    - saber.dev
  Filtered-Phrases:
    - Saber is Awesome!

############################################################
# +------------------------------------------------------+ #
# |                 AntiSpawnerMine                      | #
# +------------------------------------------------------+ #
############################################################
AntiSpawnerMine:
  Enabled: true
  Radius: 200.0

############################################################
# +------------------------------------------------------+ #
# |                  DisabledCommands                    | #
# +------------------------------------------------------+ #
############################################################
DisabledCommands:
  Enable: true
  Commands:
    - /icanhasbukkit
    - /ver
    - /version
    - /pl
    - /?
    - /plugins

############################################################
# +------------------------------------------------------+ #
# |                  StatTrack Swords                    | #
# +------------------------------------------------------+ #
############################################################
StatTrack-Swords:
  Enabled: false
  Lore:
    - '&6{date} &e{player} &fwas killed by &e{killer}'

############################################################
# +------------------------------------------------------+ #
# |                 Anti-Mob-Movement                    | #
# +------------------------------------------------------+ #
############################################################
Anti-Mob-Movement:
  - 'CREEPER'
  - 'ZOMBIE'
  - 'GHAST'
  - 'SPIDER'
  - 'BLAZE'

############################################################
# +------------------------------------------------------+ #
# |                   AntiItemDestroy                    | #
# +------------------------------------------------------+ #
############################################################
useAntiDestroySystem: true #Denies everything below to be destroyed by its specific group: Lightning, Explosion, Fire
Lightning-Deny:
  - "DIAMOND_HELMET"
  - "DIAMOND_CHESTPLATE"
  - "DIAMOND_LEGGINGS"
  - "DIAMOND_BOOTS"
  - "DIAMOND_SWORD"
  - "DIAMOND_AXE"
  - "DIAMOND_PICKAXE"
  - "MOB_SPAWNER"
  - "HOPPER"

Explosion-Deny:
  - "DIAMOND_HELMET"
  - "DIAMOND_CHESTPLATE"
  - "DIAMOND_LEGGINGS"
  - "DIAMOND_BOOTS"
  - "DIAMOND_SWORD"
  - "DIAMOND_AXE"
  - "DIAMOND_PICKAXE"
  - "MOB_SPAWNER"
  - "HOPPER"

Burn-Deny:
  - "DIAMOND_HELMET"
  - "DIAMOND_CHESTPLATE"
  - "DIAMOND_LEGGINGS"
  - "DIAMOND_BOOTS"
  - "DIAMOND_SWORD"
  - "DIAMOND_AXE"
  - "DIAMOND_PICKAXE"
  - "MOB_SPAWNER"
  - "HOPPER"

